### ISSUE TITLE
Question about hardware flow control

### ISSUE THREAD

**Issue by gitcnd** [bitmerse/WiSer#1]
Hi - are you 100% sure your hardware flow control works?

I've got a Roland Modela MDX20 milling machine, and "old" computers with physical serial ports work great, but almost all the windows USB cables (even ones that claim hardware flow control) do not actually do the flow control properly...

Your project would be amazing for my needs - milling machines make a HUGE mess and lots of noise - not anything you want next to your expensive CAD workstations :-)

**Comment by jaydeepd** [comment]
Hi @gitcnd, The hardware flow control feature underwent thorough testing with STM32 MCUs, ESP32 MCUs, Raspberry Pi and other MCUs, with RTS/CTS hardware flow control enabled. In these tests, the WiSer device performed well without any issues. So, I am confident that it will also work effectively with your milling machine. Please note that you may require a TTL-to-RS232 converter to use it in conjunction with your milling machine.

BTW, have you tried using [these USB to serial cables](https://365rolanddgnam.sharepoint.com/:b:/s/Dealers/EcfRs9hw-IBPmH7z_BcsYEsBz27kXGV5i8zlwQ3KiJ86iw)? The machine manufacturer claims that they are supported with machine.

**Comment by gitcnd** [comment]
Hi Jaydeep,

Thanks for the personal reply!

I do have that exact cable in the photo, but I'm still using a hardware serial port on a spare PC after "giving up" on a pile of other cables beforehand (the new one arrived after I gave up).

It's a tricky problem to diagnose on the Roland - since random parts of the RML stream (which looks like gcode) simply get "dropped" if the sending machine doesn't stop sending when told (when the RML buffer is full), so the problem can only be detected when the RML code arrives faster than the tool can move, and then "random crazy stuff" happens next (usually out-of-bound grinding and breaking the milling bit).

I guess the whole concept is a moot point really - if it happens not to work when I get it, since it's open-source, it can be fixed then anyhow (I'm an MCU driver-author myself already :-)

Kind Regards,
Chris Drake
