### ISSUE TITLE
5v TTL Support?

### ISSUE THREAD

**Issue by biggestsonicfan** [bitmerse/WiSer#2]
Greetings! Love the concept and idea, but I see only "3.3v" marked on the WiSer-TTL unit. Does this mean 5v TTL isn't supported or would that require component modification on the board?

**Comment by bitmerse** [comment]
Hi @biggestsonicfan, Thanks for the query. 

The WiSer-TTL has two power output pins: 5V (labeled as VCC) and 3.3V.

Regarding the serial I/O pins, they are currently 3.3V compatible. However, we are planning to add components to make them compatible with both 3.3V and 5V TTL levels in the production version.

**Comment by biggestsonicfan** [comment]
Nice, glad to hear it! Thank you! 😄

Oh but can you power the device with the serial system's 5v?

**Comment by biggestsonicfan** [comment]
[Congrats](https://www.crowdsupply.com/bitmerse/wiser/updates/wiser-now-supports-both-3-3v-and-5v-ttl-levels)!🥳

**Comment by bitmerse** [comment]
Thanks @biggestsonicfan! 

>Oh but can you power the device with the serial system's 5v?

![image](https://github.com/bitmerse/WiSer/assets/87270487/3098c6f2-3496-4f69-9c4b-a175793596a3)

Yes, you can power up the target device using WiSer-TTL's VCC pin on the serial side (marked in green).
In case you want to power-up WiSer-TTL using target device's 5V, you can connect the 5V to VCC pin on USB side (marked in red).
