### ISSUE TITLE
Antenna layout deviates from very specific MFG instruction. 

### ISSUE THREAD

**Issue by tomfleet** [bitmerse/WiSer#3]
The layout for the 2.4GHz antenna (Johanson P/N 2450AT18B100) deviates from what is given in the datasheet, and additional mfg application guidance, and will very likely have a significant impact on range. 

![image](https://github.com/bitmerse/WiSer/assets/409747/c52389af-c170-46ee-ac39-782ee3f3f5c3)

![image](https://github.com/bitmerse/WiSer/assets/409747/5e0405f1-2ce7-4f6e-87ad-69d78fe9ecf2)

The gap shown here is specified as 4mm **minimum** in the datasheet, and in other places, such as 

https://www.johansontechnology.com/chip-antenna-layout-for-802-11-applications

I think that it would possible to shift a few bits about to achieve this... Otherwise, if you are fixed on the design, I think that it would be kind to give test reports on the resultant RF performance?

**Comment by tomfleet** [comment]
In fact, the TTL version of this pair of boards has no reason **not** to have adhered to the  layout guidelines...

![image](https://github.com/bitmerse/WiSer/assets/409747/ab71d10e-d005-44e8-8d1d-3e41716b3e31)

At least that one is a very easy fix, if desired! :)

**Comment by jaydeepd** [comment]
@tomfleet, First of all, I appreciate your feedback. Thanks for pointing out the antenna layout deviation from specs. I'll review it closely and explore adjustments to meet the specified 4mm minimum gap on both the TTL and USB versions. We will incorporate these changes into the production version.

Just FYI, here are the current return loss graphs for WiSer-TTL:
![WiSer-TTL](https://github.com/bitmerse/WiSer/assets/6021718/3cb1de1e-790c-425b-bf48-27f3c275bc63)

and WiSer-USB:
![WiSer-USB](https://github.com/bitmerse/WiSer/assets/6021718/8061b2c6-ebfd-43b2-9ab2-a9294ba03a1b)

Your input is crucial; feel free to share more insights. We're committed to delivering a quality product, and every piece of feedback matters :slightly_smiling_face:
